#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

#logicielsUbuntuExports()

if   [ -f $HOME/.bashrc  ]; then settings=$HOME/.bashrc
elif [ -f $HOME/.profile ]; then settings=$HOME/.profile
else
  echo 'Unable to find suitable settings file to use !'
  exit 1
fi

if ! grep logicielsUbuntuExports $settings >/dev/null; then
  echo "export LU_PATH='`pwd`'" >> $settings
  echo ". '`pwd`/logicielsUbuntuExports'" >> $settings
  echo "LogicielsUbuntuExports successfully appended to $settings"
fi

if ! grep "alias ls='ls --color=tty'" $settings >/dev/null; then
  echo "alias ls='ls --color=tty'" >> $settings
  echo "Colored LS successfully appended to $settings"
fi

export PATH=$PATH:"$LU_PATH:$LU_PATH/Scripts"
