#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

canonMX860SetupDescription="Drivers for the Canon MX860"
canonMX860SetupStatus()
{
  return $false
}
canonMX860Setup()
{
  cd 'SetupFiles/canonMX860'

  if  [ "`uname -a | grep _64`" ]; then
    autoInstallSetup getlibsSetup getlibs
    $udo getlibs -p libgimp2.0
    $udo getlibs -p libc6
  fi

  tar -xzf cnijfilter-mx860series-3.10-1-i386-deb.tar.gz
  cd cnijfilter-mx860series-3.10-1-i386-deb/packages
  $udo dpkg -iG --force-architecture --force-depends cnijfilter-common_3.10-1_i386.deb
  $udo dpkg -iG --force-architecture --force-depends cnijfilter-mx860series_3.10-1_i386.deb
  cd ../..
  rm -rf cnijfilter-mx860series-3.10-1-i386-deb
  tar -xzf scangearmp-mx860series-1.30-1-i386-deb.tar.gz
  cd scangearmp-mx860series-1.30-1-i386-deb/packages
  $udo dpkg -iG --force-architecture --force-depends scangearmp-common_1.30-1_i386.deb
  $udo dpkg -iG --force-architecture --force-depends scangearmp-mx860series_1.30-1_i386.deb
  cd ../..
  rm -rf scangearmp-mx860series-1.30-1-i386-deb
  cd ../..

  yesOrNo 0 "install Xsane (advanced scanning software)"
  if [ $REPLY -eq $true ]; then
    eval $install xsane
  fi

  yesOrNo 0 "open Canon MX860 webpage"
  if [ $REPLY -eq $true ]; then
    firefox http://fr.canon.ch/Support/Consumer_Products/products/Fax__Multifunctionals/InkJet/PIXMA_MX_series/PIXMA_MX860.aspx
  fi
}
