#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

javaEntrepriseSetupDescription="Java : Sun Java Entreprise Edition"
javaEntrepriseSetupStatus()
{
  return `isInstalled oracle-java7-installer`
}
javaEntrepriseSetup()
{
  eval $install python-software-properties
  if ! addAptPpaRepo ppa:webupd8team/java webupd8team; then
    return $true
  fi
  #$key B725097B3ACC3965
  #$update
  eval $install oracle-java7-installer
  $udo update-java-alternatives -s java-7-oracle
  java -version
}
