#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

medibuntuSetupDescription="Encrypted DVDs unscrambling library from medibuntu repository"
medibuntuSetupStatus()
{
  [ -f '/etc/apt/sources.list.d/medibuntu.list' ] && return $true || return $false
}
medibuntuSetup()
{
  $udo wget -N http://www.medibuntu.org/sources.list.d/`lsb_release -cs`.list \
    --output-document=/etc/apt/sources.list.d/medibuntu.list
  eval $update
  eval $install --yes -q --allow-unauthenticated medibuntu-keyring
  eval $update
  eval $install libdvdcss2 ffmpeg ubuntu-restricted-extras soundconverter || return $false
  eval $install libavcodec-extra-53 || return $false
}
