#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

medibuntuSetupDescription="Encrypted DVDs unscrambling library from medibuntu repository"
medibuntuSetupStatus()
{
  [ -f '/etc/apt/sources.list.d/medibuntu.list' ] && return $true || return $false
}
medibuntuSetup()
{
  $udo wget -N http://www.medibuntu.org/sources.list.d/`lsb_release -cs`.list \
    --output-document=/etc/apt/sources.list.d/medibuntu.list
  eval $update
  eval $install --yes -q --allow-unauthenticated medibuntu-keyring
  eval $update
  eval $install libdvdcss2 ffmpeg ubuntu-restricted-extras soundconverter || return $false
  eval $install libavcodec-extra-53 || return $false
}
