#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

nemoSetupDescription='Nemo File Manager : A (good) fork of Nautilus'
nemoSetupStatus()
{
  return `isInstalled nemo`
}
nemoSetup()
{
  if ! addAptPpaRepo ppa:gwendal-lebihan-dev/cinnamon-stable gwendal; then
    return $true
  fi
  eval $install nemo nemo-fileroller || return $false
  $udo sed -i 's/NoDisplay=true/NoDisplay=false/g' \
    /etc/xdg/autostart/nemo-autostart.desktop

  # http://www.fandigital.com/2013/01/set-nemo-default-file-manager-ubuntu.html
  xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
  gsettings set org.gnome.desktop.background show-desktop-icons false
  gsettings set org.nemo.desktop show-desktop-icons true
}
