#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

nemoSetupDescription='Nemo File Manager : A (good) fork of Nautilus'
nemoSetupStatus()
{
  return `isInstalled nemo`
}
nemoSetup()
{
  if ! addAptPpaRepo ppa:gwendal-lebihan-dev/cinnamon-stable gwendal; then
    return $true
  fi
  eval $install nemo nemo-fileroller || return $false
  $udo sed -i 's/NoDisplay=true/NoDisplay=false/g' \
    /etc/xdg/autostart/nemo-autostart.desktop

  # http://www.fandigital.com/2013/01/set-nemo-default-file-manager-ubuntu.html
  xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
  gsettings set org.gnome.desktop.background show-desktop-icons false
  gsettings set org.nemo.desktop show-desktop-icons true
}
