#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

sublimeTextSetupDescription='Sublime Text 2'
sublimeTextSetupStatus()
{
  [ -d '/usr/local/SublimeText/' ] && return $true || return $false
}
sublimeTextSetup()
{
  xecho 'TODO'
  #wget -N http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.1.tar.bz2
  #wget -N 'http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.1%20x64.tar.bz2'
  #cd 'SetupFiles'
  #if ! addAptPpaRepo ppa:dominik-stadler/subversion-1.7 dominik-stadler; then
  #  return $true
  #fi
  #eval $install --reinstall subversion || return $false
}
