#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

truecryptSetupDescription="TrueCrypt : On the fly files encryption"
truecryptSetupStatus()
{
  if which truecrypt > /dev/null; then return 0; else return 1; fi
}
truecryptSetup()
{
  cd 'SetupFiles/truecrypt'
  [ "`uname -a | grep _64`" ] && arch='x64' || arch='x86'
  archive="truecrypt-7.1a-linux-$arch.tar.gz"
  setup="truecrypt-7.1a-setup-$arch"
  wget -N "http://www.truecrypt.org/download/$archive"
  tar -xzvf "$archive" || return 1
  chmod u+x "$setup"
  $udo "./$setup"
  eval $install
  cd ../..
}
