#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

wiithonSetupDescription='Wiithon : Manage USB storage of Wii games ISOs'
wiithonSetupStatus()
{
  return `isInstalled wiithon`
}
wiithonSetup()
{
  addAptRepo 'wiithon' 'http://ppa.launchpad.net/wii.sceners.linux/wiithon/ubuntu' 'main'
  $udo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1F882273
  eval $update
  eval $install wiithon
  $udo gpasswd -a $USER disk
}
