#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-flac2mp3()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Convert all FLACs from a source path to MP3s (196k stereo @48KHz)'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: $(basename $0) srcPath"
  fi

  srcPath=$1

  if [ ! -d "$srcPath" ]; then
    xecho "$srcPath doesn't exist !"
  fi

  autoInstall ffmpeg ffmpeg
  autoInstall libavcodec-extra-53 libavcodec-extra-53

  listing=/tmp/$$
  trap "rm -f '$listing' 2>/dev/null" INT TERM EXIT

  find "$srcPath" -type f -name '*.flac' > $listing
  while read flac
  do
    mecho "$flac"
    mp3=$(echo $flac | sed 's:\.flac:\.mp3:')
    ffmpeg -i "$flac" -ab 196k -ac 2 -ar 48000 -acodec libmp3lame "$mp3" </dev/null
  done < $listing

  yesOrNo $false 'remove source flac files'
  if [ $REPLY -eq $true ]; then
    find "$srcPath" -type f -name '*.mp3' > $listing
    while read mp3
    do
      flac=$(echo $mp3 | sed 's:\.mp3:\.flac:')
      rm -f "$flac"
    done < $listing
  fi
}

