#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-findContent()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Grep specific files content with a pattern'
  pecho 'Remark : .svn and .git paths are avoided !'
  pecho ''

  case $# in
  1 )  path='.'; name='*'; content=$1; extra='' ;;
  3 )  path=$1;  name=$2;  content=$3; extra='' ;;
  4 )  path=$1;  name=$2;  content=$3; extra=$4 ;;
  * )
    xecho "Usage: `basename $0` content -or- path filename content (find extra args)" ;;
  esac

  find "$path" -path "*/.svn/*" -prune -o \
               -path "*/.git/*" -prune -o \
               -type f -iname "$name" $extra \
               -exec grep -n --color=auto "$content" /dev/null {} \;
}
