#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-flac2mp3()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Convert all FLACs from a source path to MP3s (196k stereo @48KHz)'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: $(basename $0) srcPath"
  fi

  srcPath=$1

  if [ ! -d "$srcPath" ]; then
    xecho "$srcPath doesn't exist !"
  fi

  autoInstall ffmpeg ffmpeg
  autoInstall libavcodec-extra-53 libavcodec-extra-53

  listing=/tmp/$$
  trap "rm -f '$listing' 2>/dev/null" INT TERM EXIT

  find "$srcPath" -type f -name '*.flac' > $listing
  while read flac
  do
    mecho "$flac"
    mp3=$(echo $flac | sed 's:\.flac:\.mp3:')
    ffmpeg -i "$flac" -ab 196k -ac 2 -ar 48000 -acodec libmp3lame "$mp3" </dev/null
  done < $listing

  yesOrNo $false 'remove source flac files'
  if [ $REPLY -eq $true ]; then
    find "$srcPath" -type f -name '*.mp3' > $listing
    while read mp3
    do
      flac=$(echo $mp3 | sed 's:\.mp3:\.flac:')
      rm -f "$flac"
    done < $listing
  fi
}

