#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-importUtils()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'FileXYZ.lu-dep + logicielsUbuntuUtils -> FileXYZ'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: `basename $0` searchPath"
  fi

  listing=/tmp/$$
  trap "rm -f '$listing' 2>/dev/null" INT TERM EXIT
  find "$1" -type f -iname "*.lu-dep" > $listing
  while read src
  do
    dst=`dirname $src`/`basename $src .lu-dep`
    mecho "generating $dst from `basename $src`"
    cat "$src" "$LU_PATH/logicielsUbuntuUtils" > "$dst"
  done < $listing
}
