#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-pyublasCompile()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Compile a .cpp file to use as a python extension'
  mecho 'See http://documen.tician.de/pyublas/index.html'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: $(basename $0) extension"
  fi

  autoInstall python python
  autoInstallLib libboost-python-dev
  # FIXME maybe another requried package to install
  version=$(python --version 2>&1)
  version=$(expr match "$version" '.* \([0-9]\.[0-9]\).*')
  python=python$version
  i_python=/usr/include/$python
  i_pyublas=/usr/local/lib/$python/dist-packages/pyublas/include
  [ ! -d "$i_pyublas" ] && $udo pip install pyublas

  g++ -I$i_python -I$i_pyublas -fPIC -g -fpic -shared "$1.cpp" -lboost_python -l$python -o "$1.so"
}
