#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-svnRmDeleted()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Execute svn in a simple way (backup purpose)'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: `basename $0` path (. = here)"
  fi

  cd "$1" 2>/dev/null || xecho "Unable to find '$1'"

  sleep 2

  clear
  svn status | grep ^!
  yesOrNo 1 'svn rm these files'
  if [ $REPLY -eq $true ]; then
    svn status | grep ^! | while read status file
    do
      svn rm --force "$file"
    done
  fi

  a1='.~lock'
  a2='Desktop.ini'
  a3='Thumbs.db'
  clear
  svn status | grep ^? | grep -v "$a1" | grep -v "$a2" | grep -v "$a3"
  yesOrNo 1 'svn add these files'
  if [ $REPLY -eq $true ]; then
    svn status | grep ^? | while read status file
    do
      if echo $file | grep -q "$a1"; then continue; fi
      if echo $file | grep -q "$a2"; then continue; fi
      if echo $file | grep -q "$a3"; then continue; fi
      svn add "$file"
    done
  fi

  clear
  svn st
  yesOrNo 1 'commit modifications to the server'
  if [ $REPLY -eq $true ]; then
    readLine 'Please enter a one line commentary for this version (avoid ")'
    comment=$CHOICE
    svn commit -m "$comment"
  fi
}
