#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Main Developer : David Fischer (david.fischer.ch@gmail.com)
#  Copyright      : Copyright (c) 2009-2013 David Fischer. All rights reserved.
#
#******************************************************************************#
#
# This file is part of David Fischer's pyutils Project.
#
# This project is free software: you can redistribute it and/or modify it under
# the terms of the EUPL v. 1.1 as provided by the European Commission.
# This project is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.
#
# See the European Union Public License for more details.
#
# You should have received a copy of the EUPL General Public License along with
# this project. If not, see he EUPL licence v1.1 is available in 22 languages:
#     22-07-2013, <https://joinup.ec.europa.eu/software/page/eupl/licence-eupl>
#
# Retrieved from https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-svnUpdateAuthor()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Change svn:author property of all commit revisions'
  pecho ''

  if [ $# -ne 2 ]; then
    xecho "Usage: `basename $0` oldAuthor newAuthor"
  fi
  oldAuthor=$1
  newAuthor=$2

  svn log | while read line
  do
    revision=`expr match "$line" '^r\([0-9]*\) | [^ ]* |.*'`
    author=`expr match "$line" '^r[0-9]* | \([^ ]*\) |.*'`
    #author=`svn propget --revprop -r $rev svn:author`
    if [ "$revision" ]; then
      if [ ! "$author" ]; then
        xecho "[BUG] Unable to detect author for revision $revision"
      fi
      change=''
      if [ "$author" = "$oldAuthor" ]; then
        if ! svn propset --revprop -r "$revision" svn:author "$newAuthor"; then
          xecho 'Unable to change revision author property !'
        fi
        change=" -> $newAuthor"
      fi
      mecho "Revision $revision : $author$change"
    fi
  done
}
