#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-tex2pdf()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Convert a LaTeX file to a PDF'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: `basename $0` texFilename"
  fi

  texFilename=$1
  filename=`basename $texFilename .tex`

  rm -rf tex2pdf 2> /dev/null
  mkdir tex2pdf || exit 1
  trap 'rm -rf tex2pdf 2>/dev/null' INT TERM EXIT
  cp "$texFilename" tex2pdf/tmp.tex
  cp -r *.cls tex2pdf/
  cp -r images/* tex2pdf/
  cd tex2pdf
  latex tmp.tex || exit 1
  latex tmp.tex || exit 1
  dvips tmp.dvi || exit 1
  ps2pdf tmp.ps || exit 1
  mv tmp.ps "../$filename.pdf"
  cd ..
}
