#!/usr/bin/env bash

#******************************************************************************#
#               SOME SCRIPTS FOR MYSELF, AND WHY NOT FOR YOU TOO !
#
#  Author    : David Fischer
#  Contact   : david.fischer.ch@gmail.com
#  Project   : LogicielsUbuntu
#  Copyright : 2009-2013 David Fischer. All rights reserved.
#******************************************************************************#
#
# This file is part of LogicielsUbuntu.
#
# This project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this project. If not, see <http://www.gnu.org/licenses/>
#
# Retrieved from:
#   git clone https://github.com/davidfischer-ch/logicielsUbuntu.git

. logicielsUbuntuCommon

#lu-wav2flac()
{
  techo "Ubuntu's Softwares Setup Menu [Packages and Scripts]"
  techo '---------------------------- copyright David Fischer'
  techo ''
  pecho 'Convert all WAVs from a source path to FLACs'
  pecho ''

  if [ $# -ne 1 ]; then
    xecho "Usage: $(basename $0) srcPath"
  fi

  srcPath=$1

  if [ ! -d "$srcPath" ]; then
    xecho "$srcPath doesn't exist !"
  fi

  autoInstall flac flac

  find "$srcPath" -type f -name '*.wav' | \
  while read wav
  do
    flac=$(echo $wav | sed 's:.wav:.flac:')
    flac --best --keep-foreign-metadata "$wav" "$flac"
  done
  yesOrNo $false 'remove source wav files'
  if [ $REPLY -eq $true ]; then
    find "$srcPath" -type f -name '*.wav' -exec rm -f {} \;
  fi
}

